name: Manual Build AArch64

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Enable ARM64 emulator
        uses: docker/setup-qemu-action@v3

      - name: Build in Debian 10 ARM64 (glibc 2.28)
        run: |
          docker run --rm --platform=linux/arm64 \
            -v $PWD:/src \
            debian:buster \
            bash -c "
              apt-get update &&
              apt-get install -y cmake build-essential libsdl2-dev libsdl2-image-dev libsdl2-ttf-dev &&
              cd /src &&
              cmake -Bbuild -DCMAKE_BUILD_TYPE=RelWithDebInfo &&
              cmake --build build -j4
            "

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: sdl2imgshow-aarch64
          path: build/sdl2imgshow
